"use client";

import { useState } from "react";
import Link from "next/link";
import {
  CheckCircle2,
  Circle,
  Send,
  Loader2,
  LayoutDashboard,
  Download,
  AlertTriangle,
  BadgeCheck,
  Search,
} from "lucide-react";
import { PortalShell } from "@/components/portal/shell";
import { useAccount } from "@/components/portal/use-account";
import { getProgress, submitApplication } from "@/lib/portal";
import { cn, formatDateTime } from "@/lib/utils";

export default function SubmitPage() {
  return (
    <PortalShell title="Submit Application">
      <SubmitBody />
    </PortalShell>
  );
}

const NEXT_STEPS = [
  {
    n: 1,
    title: "LPB Review",
    text: "Your information and documents will be reviewed by a Liberia Pharmacy Board data officer.",
  },
  {
    n: 2,
    title: "Verification",
    text: "You may be contacted for additional information if anything needs clarification.",
  },
  {
    n: 3,
    title: "Approval",
    text: "Once verified, your registration status will be updated and confirmed on this portal.",
  },
];

function SubmitBody() {
  const { account, setAccount } = useAccount();
  const [submitting, setSubmitting] = useState(false);
  const [error, setError] = useState<string>();
  const [justSubmitted, setJustSubmitted] = useState(false);

  if (!account) return null;
  const metrics = getProgress(account);
  const alreadySubmitted = ["submitted", "under_review", "verified"].includes(account.applicationStatus);

  async function submit() {
    if (!account) return;
    setError(undefined);
    setSubmitting(true);
    const { account: updated, error } = await submitApplication(account.id);
    setSubmitting(false);
    if (error || !updated) {
      setError(error ?? "Submission failed.");
      return;
    }
    setAccount(updated);
    setJustSubmitted(true);
    window.scrollTo({ top: 0, behavior: "smooth" });
  }

  function downloadReceipt() {
    if (!account) return;
    const lines = [
      "LIBERIA PHARMACY BOARD, NATIONAL PHARMACIST REGISTRY",
      "2026 National Pharmacist Census · Submission Receipt",
      "======================================================",
      `Registry reference : ${account.registryRef ?? "not yet issued"}`,
      `Name               : ${[account.personal.title, account.personal.firstName, account.personal.middleName, account.personal.surname].filter(Boolean).join(" ")}`,
      `LPB license no.    : ${account.licensure.lpbNumber ?? "not provided"}`,
      `Email              : ${account.email}`,
      `Phone              : ${account.contact.phone ?? "not provided"}`,
      `County             : ${account.contact.county ?? "not provided"}`,
      `Submitted          : ${formatDateTime(account.submittedAt)}`,
      `Status             : Submitted, awaiting LPB review`,
      "======================================================",
      "Keep this receipt. Quote your registry reference at license",
      "renewal and in any correspondence with the Board.",
      "",
      "This receipt was generated by the LPB digital registry (demo build).",
    ].join("\n");
    const blob = new Blob([lines], { type: "text/plain;charset=utf-8" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `${account.registryRef ?? "lpb-receipt"}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  }

  /* ---------------- success state ---------------- */
  if (justSubmitted || (alreadySubmitted && account.registryRef)) {
    return (
      <div className="mx-auto max-w-2xl space-y-5">
        <div className="card overflow-hidden text-center">
          <div className="band-navy px-8 py-10 text-white">
            <span className="mx-auto flex h-20 w-20 items-center justify-center rounded-full bg-white/15 ring-8 ring-white/10">
              <CheckCircle2 className="h-11 w-11 text-accent-300" />
            </span>
            <h2 className="mt-5 text-2xl font-extrabold tracking-tight sm:text-3xl">
              Application Submitted Successfully!
            </h2>
            <p className="mx-auto mt-2 max-w-md text-sm text-white/75">
              Your pharmacist registry application has been submitted. You will be notified once it has been
              reviewed by the Liberia Pharmacy Board.
            </p>
          </div>
          <div className="px-8 py-7">
            <div className="rounded-sm border-2 border-dashed border-accent-300 bg-accent-50/50 px-6 py-5">
              <p className="text-xs font-bold uppercase tracking-[0.2em] text-accent-700">Registry reference</p>
              <p className="mt-1 font-mono text-3xl font-extrabold tracking-wide text-brand-950">{account.registryRef}</p>
              <p className="mt-1 text-xs text-slate-500">Submitted {formatDateTime(account.submittedAt)}</p>
            </div>
            <div className="mt-6 flex flex-wrap justify-center gap-3">
              <Link href="/portal" className="btn-primary">
                <LayoutDashboard className="h-4 w-4" /> Back to Dashboard
              </Link>
              <button type="button" onClick={downloadReceipt} className="btn-outline">
                <Download className="h-4 w-4" /> Download Receipt
              </button>
            </div>
          </div>
        </div>

        <div className="card p-6">
          <h3 className="font-bold text-brand-950">What happens next?</h3>
          <ol className="mt-4 space-y-4">
            {NEXT_STEPS.map((s) => (
              <li key={s.n} className="flex gap-4">
                <span className="flex h-8 w-8 shrink-0 items-center justify-center rounded-full bg-brand-800 text-sm font-bold text-white">
                  {s.n}
                </span>
                <div>
                  <p className="text-sm font-bold text-slate-800">{s.title}</p>
                  <p className="mt-0.5 text-sm text-slate-600">{s.text}</p>
                </div>
              </li>
            ))}
          </ol>
        </div>
      </div>
    );
  }

  /* ---------------- readiness checklist ---------------- */
  return (
    <div className="mx-auto max-w-2xl space-y-5">
      <div className="card p-6">
        <div className="flex items-center justify-between">
          <h3 className="font-bold text-brand-950">Before you submit</h3>
          <span className={cn("chip", metrics.progressPct === 100 ? "bg-accent-100 text-accent-800" : "bg-amber-100 text-amber-800")}>
            {metrics.progressPct}% complete
          </span>
        </div>
        <p className="mt-1 text-sm text-slate-500">
          The Board can only verify complete applications. Confirm each item below:
        </p>
        <ul className="mt-5 space-y-3">
          {metrics.checks.map((c) => (
            <li
              key={c.key}
              className={cn(
                "flex items-center justify-between gap-3 rounded-sm border px-4 py-3.5",
                c.done ? "border-accent-200 bg-accent-50/50" : "border-slate-200 bg-white"
              )}
            >
              <span className="flex items-center gap-3">
                {c.done ? (
                  <CheckCircle2 className="h-5 w-5 shrink-0 text-accent-500" />
                ) : (
                  <Circle className="h-5 w-5 shrink-0 text-slate-300" />
                )}
                <span className={cn("text-sm font-semibold", c.done ? "text-accent-900" : "text-slate-600")}>{c.label}</span>
              </span>
              {!c.done && c.key === "documents" && metrics.missingRequiredDocs.length > 0 && (
                <span className="text-xs text-amber-700">Missing: {metrics.missingRequiredDocs.join(", ")}</span>
              )}
            </li>
          ))}
        </ul>

        {metrics.progressPct < 100 && (
          <div className="mt-5 flex items-start gap-3 rounded-sm border border-amber-200 bg-amber-50 px-4 py-3">
            <AlertTriangle className="mt-0.5 h-4 w-4 shrink-0 text-amber-600" />
            <p className="text-sm text-amber-800">
              Complete the outstanding items to enable submission.{" "}
              <Link href="/portal/profile" className="font-bold underline">Profile</Link> ·{" "}
              <Link href="/portal/education" className="font-bold underline">Qualifications</Link> ·{" "}
              <Link href="/portal/documents" className="font-bold underline">Documents</Link>
            </p>
          </div>
        )}
      </div>

      <div className="card p-6">
        <h3 className="flex items-center gap-2 font-bold text-brand-950">
          <BadgeCheck className="h-4 w-4 text-brand-600" /> Final declaration
        </h3>
        <p className="mt-3 text-sm leading-relaxed text-slate-600">
          By submitting, you declare that the information in your profile, credentials and documents is true,
          complete and accurate, and you consent to the Liberia Pharmacy Board processing it for the purposes of
          the 2026 National Pharmacist Census and license verification.
        </p>
        {error && (
          <p className="mt-4 rounded-lg border border-red-200 bg-red-50 px-3.5 py-2.5 text-sm font-medium text-red-700">
            {error}
          </p>
        )}
        <button
          type="button"
          onClick={submit}
          disabled={submitting || metrics.progressPct < 100}
          className="btn-accent mt-5 w-full py-3 text-base"
        >
          {submitting ? <Loader2 className="h-5 w-5 animate-spin" /> : <Send className="h-4 w-4" />}
          {submitting ? "Submitting to the LPB…" : "Submit Application"}
        </button>
        <p className="mt-3 flex items-center justify-center gap-1.5 text-xs text-slate-400">
          <Search className="h-3 w-3" /> You can track your status anytime on the dashboard.
        </p>
      </div>
    </div>
  );
}
